apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 443

  - name: http
    port: 80
    targetPort: 80

  selector:
    app: nginx
